import '@/shared/styles/global.css';

import type { Metadata } from 'next';

import { Main } from '@/shared/layout';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-theme="pastel">
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
